name: CI and tests

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  license-check:
    name: License check
    runs-on: ubuntu-latest

    steps:
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8
          run_install: false

      - name: Setup Gluon
        run: pnpm i

      - name: Check license
        run: pnpm run gluon lc
